services:
  frontend:
    build:
      context: ./lmsfrontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network
    volumes:
      - ./lmsfrontend:/app

  backend:
    build:
      context: ./lmsbackend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./lmsbackend:/app
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: lms
      POSTGRES_USER: lmsuser
      POSTGRES_PASSWORD: lmspass
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  nginx:
    build:
      context: ./lmsnginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  dbdata:
  frontend:
  backend:

networks:
  app-network:
    driver: bridge
